export enum TransactionType{
    REGULAR = 1,
    FREESPIN = 10,
    RESPIN = 30,
    RESPIN_IN_FREESPIN = 31,
    REGULAR_MYSTERIES = 40,
    FREESPIN_MYSTERIES= 41,
    RESPIN_MYSTERIES = 42,
    RESPIN_IN_FREESPIN_MYSTERIES = 43
}